### ISSUE TITLE
i don't know how to proceed 

### ISSUE THREAD

**Issue by 1997mohan** [danic85/mojo_home_bot#25]
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# cd virtual_assistant
root@raspberrypi:/home/pi/virtual_assistant# python main.py startx
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.19.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python2.7/dist-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Enter value for config 'Admin':

**Comment by danic85** [comment]
The master branch is python 3.x but you're running this script in python 2.7.

Can you try installing the dependencies on python 3 and then executing the startx command on python 3?

**Comment by 1997mohan** [comment]
Respected sir
I'm a final year ECE student from India. I'm using your virtual assistant repository as a final year project. I'm getting lot of errors since I'm new to this field I'm not capable of rectifying those errors in a correct manner already I have shared a pic in the git hub repository which I got as a error. 
So sir kindly guide me with full instructions with step by step is there any other website which is similar to this please kindly share that to me or if any YouTube video is similar to this kindly share that too.
Hoping for your response
Thankyou

**Comment by danic85** [comment]
Happy to help if you'd like to try the suggestion in my previous comment.

**Comment by 1997mohan** [comment]
Definitely sir thank you

**Comment by 1997mohan** [comment]
pymongo.errors.ConfigurationError: Server at localhost:27017 reports wire versio
n 0, but this version of PyMongo requires at least 2 (MongoDB 2.6).

**Comment by danic85** [comment]
It looks like you don't have the appropriate dependencies installed for pymongo. A quick google search brought back this article:
https://stackoverflow.com/questions/48060354/configurationerror-server-at-127-0-0-127017-reports-wire-version-0-but-this-v

**Comment by 1997mohan** [comment]
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# cd virtual_assistant
root@raspberrypi:/home/pi/virtual_assistant# sudo apt-get install mongodb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mongodb is already the newest version (1:2.4.14-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberrypi:/home/pi/virtual_assistant# set config user_id1=531286516
root@raspberrypi:/home/pi/virtual_assistant# set config user_id2=532177899
root@raspberrypi:/home/pi/virtual_assistant# set config user_id=531286516
root@raspberrypi:/home/pi/virtual_assistant# set config telegram_bot_key=

am i going correct? if not pls correct me
